########################### CASTLE'S ENVIRONMENT
# Here are my 2 Docker Hosts:
# - Network Area Storage (nas) - Synology DS1522+
# - Media / Minecraft Server (mms) - Some rando computer with Ubuntu Server 22.04

########################### THIS COMPOSE FILE
# - Media / Minecraft Server (mms) - Some rando computer with Ubuntu Server 22.04
# - Prefix/suffix "mms" refers to the above host
# - Docker version 20.10.7, build f0df350 # newer than the guide, 24.0.7, build afdd53b
# - Docker Compose version 1.24.1, build 4667896b # newer than the guide, v2.21.0

name: Media Minecraft Server

########################### NETWORKS
# You may customize the network subnets (192.168.x.0/24) below as you please.
networks:
  default:
    driver: bridge
  dockervlan:
    name: dockervlan
    driver: mcvlan
      parent: enp3s0 # was eth0 in example, using ifconfig
    ipam:
      config:
        - subnet: 192.168.10.0/24
          ip_range: "192.168.10.266/32"
          gateway: "192.168.1.1"

########################### SECRETS
secrets:
  plex_claim:
    file: $DOCKERDIR/secrets/plex_claim
  mysql_root_password:
    file: $DOCKERDIR/secrets/mysql_root_password # NOT SETUP

include:
  ########################### SERVICES
  # PREFIX mms = Media / Minecraft Server
  # HOSTNAME=mds - defined in .env
  
  # From current compose: mc_java, plex, watchtower

  # MEDIA
  #- compose/$HOSTNAME/airsonic-advanced.yml # EXCLUDED
  #- compose/$HOSTNAME/jellyfin.yml # EXCLUDED
  - compose/$HOSTNAME/plex.yml
  # - compose/$HOSTNAME/plex-image-cleanup.yml
  # - compose/$HOSTNAME/plex-meta-manager.yml
  #- compose/$HOSTNAME/tautulli.yml 
  
  # Minecraft
  - compose/$HOSTNAME/mc_java.yml

  # DATABASES
  #- compose/$HOSTNAME/prometheus.yml
  #- compose/$HOSTNAME/mariadb.yml
  #- compose/$HOSTNAME/influxdb.yml

  # MONITORING
  #- compose/$HOSTNAME/node-exporter.yml